LR: 2.5e-4
NUM_ENVS: 16
SEED: 30
NUM_STEPS: 128
TOTAL_TIMESTEPS: 30000000
LOG_FREQUENCY: 10000000
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.00
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "relu"
ENV_NAME: "MiniSMAC"
ENV_KWARGS: {}
ANNEAL_LR: True
DISABLE_JIT: False
ENTITY: ""
PROJECT: ""
WANDB_MODE: "disabled"
NUM_SEEDS: 5
NUM_ACTORS: ???
NUM_UPDATES: ???
MINIBATCH_SIZE: ???
NUM_OUTER_LOOPS: ???