LR: 2.5e-4
NUM_ENVS: 16
SEED: 30
NUM_STEPS: 128
TOTAL_TIMESTEPS: 1e4
LOG_FREQUENCY: 1e7
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
ENT_COEF: 0.00
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "relu"
ENV_NAME: "MPE_simple_spread_v3"
ENV_KWARGS: {}
ANNEAL_LR: True
SAVE_GIF: False
EVALUATE_ONLY: False
CHECKPOINTS_TO_RESTORE: Null
CHECKPOINT_MAP_NAMES: Null
SAVE_RUNNER_STATE: True
DISABLE_JIT: False
ENTITY: ???
PROJECT: ???
WANDB_MODE: "disabled"
NUM_SEEDS: 5
NUM_ACTORS: ???
NUM_UPDATES: ???
MINIBATCH_SIZE: ???
NUM_OUTER_LOOPS: ???