"LR": 4e-3
"NUM_ENVS": 32 # must be a multiple of 8
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.04
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.00
"VF_COEF": 0.5
"MAX_GRAD_NORM": 10.0
"ACTIVATION": "relu"
"ENV_NAME": "MPE_simple_spread_v3"
"SEED": 30
"NUM_SEEDS": 10
"ENV_KWARGS": {}


"DISABLE_JIT": False
"WANDB_MODE": "online"
"ANNEAL_LR": True
"ENTITY": "amacrutherford"
"PROJECT": "mpe-rnn"
"DEVICE": 0