LR: 5e-4
NUM_ENVS: 25
SEED: 20
NUM_STEPS: 128
TOTAL_TIMESTEPS: 1e6
LOG_FREQUENCY: 1e7
UPDATE_EPOCHS: 5
NUM_MINIBATCHES: 2
GAMMA: 0.99
GAE_LAMBDA: 1.0
CLIP_EPS: 0.3
SCALE_CLIP_EPS: False
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 0.5
ACTIVATION: "tanh"
ENV_NAME: "MPE_simple_spread_v3"
ENV_KWARGS: {}
ANNEAL_LR: True
SAVE_GIF: False
EVALUATE_ONLY: False
CHECKPOINTS_TO_RESTORE: Null
CHECKPOINT_MAP_NAMES: Null
SAVE_RUNNER_STATE: True
DISABLE_JIT: False
DEVICE: 0
ENTITY: "amacrutherford"
PROJECT: "mpe-rnn"
WANDB_MODE: "online"
NUM_SEEDS: 30
NUM_ACTORS: ???
NUM_UPDATES: ???
MINIBATCH_SIZE: ???
NUM_OUTER_LOOPS: ???