entity: amacrutherford
project: smax-rnn
program: mappo_smax_rnn.py
command:
  - python3
  - ${program}
  - ${args_no_hyphens}
method: grid
parameters:
  LR: 
    values:
      - 2.0e-3
      - 8.0e-3
      - 5.0e-4
  NUM_ENVS: 
    values:
      - 64
  SEED: 
    values:
      - 0
  NUM_STEPS: 
    values:
      - 128
  TOTAL_TIMESTEPS: 
    values: 
      - 10000000
  UPDATE_EPOCHS: 
    values:
      - 2
      - 4
      - 8
  NUM_MINIBATCHES: 
    values:
      - 2
      - 4
  GAMMA: 
    values: 
      - 0.99
  GAE_LAMBDA: 
    values:
      - 0.95
  CLIP_EPS: 
    values:
      - 0.05
      - 0.1
      - 0.2
  SCALE_CLIP_EPS:
    values:
      - True
      - False
  ENT_COEF: 
    values:
      - 0.00
  VF_COEF: 
    values:
      - 0.5
  MAX_GRAD_NORM: 
    values:
      - 0.5
  ENV_NAME: 
    values:
      - "HeuristicEnemyMiniSMAC"
  MAP_NAME: 
    values:
      - "27m_vs_30m"
      - "3s_vs_5z"
      - "smacv2_20_units"

  ANNEAL_LR: 
    values:
      - True