"program": "mappo_mpe.py"
"method": "random"
"metric": {"goal": "maximize", "name": "returns"}
"parameters": {
    "LR": {"values": [1.0e-5, 1.0e-4, 2.5e-3, 1.0e-3]},
    "NUM_ENVS": {"values": [16, 32, 64, 128]},
    "NUM_STEPS": {"values": [16, 64, 128, 256]},
    "UPDATE_EPOCHS": {"values": [1, 2, 4, 8]},
    "NUM_MINIBATCHES": {"values": [1, 2, 4, 8]},
    "GAE_LAMBDA": {"values": [0.9, 0.95, 0.99]},
    "CLIP_EPS": {"values": [0.1, 0.2, 0.3]},
    "ENT_COEF": {"values": [0.01, 0.05, 0.1]},
    "VF_COEF": {"values": [0.1, 0.5, 1.0]},
    "MAX_GRAD_NORM": {"values": [0.1, 0.5, 1.0]},
    "ACTIVATION": {"values": ["tanh", "relu"]},
}

"command":  
  - python 
  - ${program}
  - ${args_no_hyphens}
