"LR": 2.5e-4
"NUM_ENVS": 16
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.05
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS": {}
"ANNEAL_LR": True
"DISABLE_JIT": False
"SEED": 20
"DEVICE": 0

"WANDB_MODE": "online"
"ENTITY": "amacrutherford"
"PROJECT": "mpe-rnn"