"LR": 5e-4
"NUM_ENVS": 25
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1e6
"UPDATE_EPOCHS": 5
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 1.0
"CLIP_EPS": 0.3
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS": {}
"ANNEAL_LR": True
"DISABLE_JIT": False
"SEED": 20
"NUM_SEEDS": 30
"DEVICE": 0

"WANDB_MODE": "online"
"ENTITY": "amacrutherford"
"PROJECT": "mpe-rnn"